# See https://upptime.js.org/docs/configuration for more options

# Github org/repo
owner: joinyearone
repo: upptime

# Sites we ping to report status
sites:
  - name: YearOne product
    url: https://app.joinyearone.io
  - name: YearOne marketing
    url: https://joinyearone.io
  - name: Fake Site Test
    url: https://thisisnotarealsite.com

# Configs for the status page display
status-website:
  name: YearOne
  cname: status.joinyearone.io
  logoUrl: https://app.joinyearone.io/assets/yearone_logo-b1e0b3736079cbf0d67d21c860f748ec4b64673073f06b959731c2cc1361a402.png
  favicon: https://app.joinyearone.io/favicons/favicon-192.png
  introTitle: "**YearOne**, growing software engineers one lesson at a time"
  introMessage: Live status updates about the YearOne sites.
  navbar:
    - title: Status
      href: /
    - title: Product
      href: https://app.joinyearone.io
    - title: Homepage
      href: https://joinyearone.io
  css: ".logo.svelte-a08hsz img.svelte-a08hsz { height: fit-content; } .logo.svelte-a08hsz img.svelte-a08hsz + div { visibility: hidden; }"
